### ISSUE TITLE
Change Aptos and Sui packages into an OR relationship

### ISSUE THREAD

**Issue by lispking** [amp-buildpacks/move#6]
* Replace `buildpack.toml` to below context:

```toml
[[order]]
  [[order.group]]
    id = "amp-buildpacks/aptos"
    version = "0.1.3"
  
  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.8"

[[order]]
  [[order.group]]
    id = "amp-buildpacks/sui"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.8"
```
